### ISSUE TITLE
Determine core pallets to onboard

### ISSUE THREAD

**Issue by geastwood** [litentry/governance2-testnet#1]
# List of pallets to be integrated

link: https://github.com/paritytech/substrate/tree/master/frame

* [x] treasury
* [x] tips
* [x] balances
* [x] democracy
* [x] referenda
* [x] scheduler
* [x] balance
* [x] bounties
* [ ] staking
* [ ] auctions

**Comment by geastwood** [comment]
@rrtti would you also take a look at this list, to confirm whether it's complete.

**Comment by rrtti** [comment]
we should add auctions and staking as well, if possible: governance has direct effects on both.

**Comment by geastwood** [comment]
> we should add auctions and staking as well, if possible: governance has direct effects on both.

Thanks, updated

**Comment by geastwood** [comment]
@chenzongxiong what about the last two pallets?

**Comment by chenzongxiong** [comment]
@geastwood 
As for staking pallet, it involves other pallets, e.g. session, session history, election, pallets. It's a bit complex for us to integrate so many pallets at this round. 

I can merge current pallet to main branch if other guys need this dev chain, and no dependencies with **staking** palelts.

**Comment by geastwood** [comment]
Yeh, you can merge the this PR and set up a RPC node, the other pallets can be onboard a bit later. Thank you.

**Comment by chenzongxiong** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fgovernance2-testnet.litentry.io#/explorer

**Comment by geastwood** [comment]
Close in favor of #5
